---
name: run-distronode-lint
description: Run Distronode Lint
author: Distronode by Red Hat <info@distronode.com>
branding:
  icon: shield
  color: red
inputs:
  args:
    description: Arguments to be passed to distronode-lint command.
    required: false
    default: ""
  setup_python:
    description: If false, this action will not setup python and will instead rely on the already installed python.
    required: false
    default: true
  working_directory:
    description: The directory where to run distronode-lint from. Default is `github.workspace`.
    required: false
    default: ""
runs:
  using: composite
  steps:
    - name: Process inputs
      id: inputs
      shell: bash
      run: |
        if [[ -n "${{ inputs.working_directory }}" ]]; then
          echo "working_directory=${{ inputs.working_directory }}" >> $GITHUB_OUTPUT
        else
          echo "working_directory=${{ github.workspace }}" >> $GITHUB_OUTPUT
        fi

    # Due to GHA limitation, caching works only for files within GITHUB_WORKSPACE
    # folder, so we are forced to stick this temporary file inside .git, so it
    # will not affect the linted repository.
    # https://github.com/actions/toolkit/issues/1035
    # https://github.com/actions/setup-python/issues/361
    - name: Generate .git/distronode-lint-requirements.txt
      shell: bash
      env:
        GH_ACTION_REF: ${{ github.action_ref || 'main' }}
      working-directory: ${{ steps.inputs.outputs.working_directory }}
      run: |
        wget --output-document=.git/distronode-lint-requirements.txt https://raw.githubusercontent.com/distronode/distronode-lint/$GH_ACTION_REF/.config/lock-requirements.txt

    - name: Set up Python
      if: inputs.setup_python == 'true'
      uses: actions/setup-python@v4
      with:
        cache: pip
        cache-dependency-path: ${{ steps.inputs.outputs.working_directory }}/.git/distronode-lint-requirements.txt
        python-version: "3.11"

    - name: Install distronode-lint
      shell: bash
      env:
        GH_ACTION_REF: ${{ github.action_ref || 'main' }}
      # We need to set the version manually because $GITHUB_ACTION_PATH is not
      # a git clone and setuptools-scm would not be able to determine the version.
      # git+https://github.com/distronode/distronode-lint@${{ github.action_ref || 'main' }}
      # SETUPTOOLS_SCM_PRETEND_VERSION=${{ github.action_ref || 'main' }}
      run: |
        cd $GITHUB_ACTION_PATH
        pip install "distronode-lint[lock] @ git+https://github.com/distronode/distronode-lint@$GH_ACTION_REF"
        distronode-lint --version

    - name: Run distronode-lint
      shell: bash
      working-directory: ${{ steps.inputs.outputs.working_directory }}
      run: distronode-lint ${{ inputs.args }}
