---
- name: Fixture
  hosts: webservers
  vars:
    varset: varset
  tasks:
    - name: I am a block
      block:
        - name: Include under block
          distronode.builtin.include_tasks: tasks/nestedincludes.yml
        # - block:
        #     - include_tasks: "{{ varnotset }}.yml"
      rescue:
        - name: Include under rescue
          distronode.builtin.include_tasks: "{{ varset }}.yml"
      always:
        - name: Include under always
          distronode.builtin.include_tasks: tasks/directory with spaces/main.yml
