---
- name: Fixture for test_files_not_scanned_twice
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Some include
      distronode.builtin.import_tasks: tasks/included-with-lint.yml
    - name: Some include_tasks with file and jinja2
      distronode.builtin.include_tasks:
        file: "{{ 'tasks/included-with-lint.yml' }}"
