---
- hosts: localhost
  name: BANNED
- hosts: localhost
  name: Another BANNED line
  tasks:
    - name: Foo
      debug:
        msg: A 3rd BANNED line

    - name: Bar
      distronode.builtin.command: echo something
      changed_when: false
