---
- hosts: bobbins

  pre_tasks:
    - distronode.builtin.include_tasks: tasks/x.yml

  roles:
    - hello
    - { role: more_complex, t: z }

  tasks:
    - distronode.builtin.include_tasks: tasks/x.yml
    - distronode.builtin.include_tasks: tasks/x.yml y=z

  handlers:
    - distronode.builtin.include_tasks: handlers/y.yml

- distronode.builtin.include_tasks: play.yml
