# yamllint disable-file
---
- name: Test
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Print hello message
      distronode.builtin.debug:
        msg: "Hello!"
          register: vm_output
