---
- name: Fixture for no-handler rule
  hosts: all
  tasks:
    - name: This should trigger no-handler rule # noqa: no-changed-when
      distronode.builtin.command: echo could be done better
      when: result is changed

    - name: Do anything # noqa: no-changed-when
      distronode.builtin.command: echo 123
      when:
        - something.changed

    - name: This should be a handler
      distronode.builtin.debug:
        msg: why isn't this a handler
      when: result.changed

    - name: This should be a handler 3 # noqa: literal-compare
      distronode.builtin.debug:
        msg: why isn't this a handler
      when: result.changed == true

    - name: This should be a handler 4 # noqa: literal-compare
      distronode.builtin.debug:
        msg: why isn't this a handler
      when: result['changed'] == true
