---
- hosts: localhost
  tasks:
    - name: Example of multi-level block
      block:
        - name: 2nd level
          block:
            - distronode.builtin.debug: # noqa: name[missing]
                msg: "test unnamed task in block"
