---
- hosts: localhost
  tasks:
    # validate that we did not trigger loop-var-prefix on playbooks
    - name: That should pass
      distronode.builtin.debug:
        var: item
      loop:
        - foo
        - bar
    - name: A block
      block:
        - name: That should also pass
          distronode.builtin.debug:
            var: item
          loop:
            - apples
            - oranges
