---
- name: Fixture
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - distronode.builtin.command:
        cmd: echo "no name" # should generate name[missing]
    - name: Another task
      distronode.builtin.debug:
        msg: debug message
