---
- name: Fixture for src/distronodelint/rules/name.py::test_name_template(
  hosts: all
  tasks:
    - name: This task {{ sampleService }} name is not correctly templated
      distronode.builtin.command: echo "Hello World"
      changed_when: false
    - name: This task is correctly templated {{ sampleService }}
      distronode.builtin.command: echo "Hello World"
      changed_when: false
    - name: This task is correctly templated '{{ sampleService }}'
      distronode.builtin.command: echo "Hello World"
      changed_when: false
