---
- name: Example with discouraged free-form syntax
  hosts: localhost
  tasks:
    - name: Create a placefolder file
      distronode.builtin.command:
        cmd: touch foo
        chdir: /tmp
      changed_when: false
    - name: Use raw to echo
      distronode.builtin.raw: echo foo
      args:
        executable: /bin/bash
      changed_when: false
    - name: Configure locale
      # https://github.com/distronode/distronode-lint/issues/2573
      distronode.builtin.command: localectl set-locale LANG=en_GB.UTF-8
      when: not distronode_check_mode
      changed_when: false
