---
- name: Fixture for testing risky-octal rule
  hosts: hosts
  vars:
    varset: varset
  tasks:
    - name: Octal permissions test fail (600)
      distronode.builtin.file:
        path: foo
        mode: 600

    - name: Octal permissions test fail (710)
      distronode.builtin.file:
        path: foo
        mode: 710

    - name: Octal permissions test fail (123)
      distronode.builtin.file:
        path: foo
        mode: 123

    - name: Octal permissions test fail (2000)
      distronode.builtin.file:
        path: bar
        mode: 2000
