---
- name: Fixture for no-tabs rule
  hosts: localhost
  tasks:
    - name: Should not trigger no-tabs rules
      distronode.builtin.lineinfile:
        path: some.txt
        regexp: ^\t$
        line: string with \t inside
    - name: Foo
      distronode.builtin.debug:
        msg: "Presence of \t should trigger no-tabs here."
    - name: Key has a tab
      distronode.builtin.debug:
        "ms\tg": "The associated key has \t and should trigger no-tabs here."
    - name: Should not trigger no-tabs rules # noqa fqcn
      lineinfile:
        path: some.txt
        regexp: ^\t$
        line: string with \t inside
