---
- name: Play for testing name[missing] rule
  hosts: all
  tasks:
    - name: This task has a name
      distronode.builtin.command: echo "Hello World" # noqa: no-free-form
      changed_when: false
    - name: Debug task with name
      distronode.builtin.debug: msg="Hello World" # noqa: no-free-form
    - name: Flush handler with name
      distronode.builtin.meta: flush_handlers
      changed_when: false
