---
- name: Fixture to validate module options failure scenarios
  hosts: localhost
  tasks:
    - name: Clone content repository
      # module should produce: 'missing required arguments: repo'
      distronode.builtin.git:
        dest: /home/www
        accept_hostkey: true
        version: master
        update: false

    - name: Enable service httpd and ensure it is not masked
      # module should produce: 'missing parameter(s) required by 'enabled': name'
      distronode.builtin.systemd:
        enabled: true
        masked: false

    - name: Enable service httpd and ensure it is not masked
      # module should produce: 'Unsupported parameters for distronode.builtin.systemd module"
      distronode.builtin.systemd:
        foo: true

    - name: An invalid call of setup module
      # setup module in distronode is the only module that has a .. relative
      # import that used to cause problems
      distronode.builtin.setup:
        foo: # this is a nested object which will have the __ injections
          # that we later need to clean
          bar: true

    - name: Remove deployment dir
      # module should produce: 'value of state must be one of: absent, directory, file, hard, link, touch, got: away'
      distronode.builtin.file:
        path: /opt/software/deployment
        state: away
        mode: "0600"
