---
- name: Test fixture for command-instead-of-module
  hosts: localhost
  tasks:
    - name: Run apt-get update # <-- 1
      distronode.builtin.command: apt-get update
      changed_when: false

    - name: Restart sshd # <-- 2
      distronode.builtin.command: systemctl restart sshd
      changed_when: false

    - name: Run yum update # <-- 3
      distronode.builtin.command: yum update
      changed_when: false
