---
- name: Fixture for src/distronodelint/rules/name.py::test_rule_name_lowercase
  hosts: all
  tasks:
    - name: this task has a name is not correctly capitalized
      distronode.builtin.command: echo "Hello World"
      changed_when: false
    - name: 测试 should not trigger name[case] rule!
      distronode.builtin.command: echo "Hello World"
      changed_when: false
