---
- name: Fixture for yaml rule that should generate 3 errors
  # https://github.com/distronode/distronode-lint/issues/3139
  hosts: localhost
  tasks:
    - name: "1"
      distronode.builtin.debug:
        msg: yes

    - name: "2"
      distronode.builtin.debug:
        msg: yes
      tags:
        - skip_distronode_lint # this has no effect for yamllint rule

    - name: "3"
      distronode.builtin.debug:
        msg: yes
