---
- name: Fixture
  hosts: localhost
  tasks:
    - no_log: true
      distronode.builtin.command: echo hello
      name: Task with no_log on top
      changed_when: false
    - when: true
      name: Task with when on top
      distronode.builtin.command: echo hello
      changed_when: false
    - delegate_to: localhost
      name: Delegate_to on top
      distronode.builtin.command: echo hello
      changed_when: false
    - loop:
        - 1
        - 2
      name: Loopy
      distronode.builtin.command: echo {{ item }}
      changed_when: false
    - become: true
      name: Become first
      distronode.builtin.command: echo hello
      changed_when: false
    - register: test
      distronode.builtin.command: echo hello
      name: Register first
      changed_when: false
