---
- name: Test fixture complexity rule
  hosts: all
  tasks:
    - name: Task 1
      distronode.builtin.debug:
        msg: "This is task 1"

    - name: Task 2
      distronode.builtin.debug:
        msg: "This is task 2"

    - name: Task 3
      distronode.builtin.debug:
        msg: "This is task 3"

    - name: Task 4
      distronode.builtin.debug:
        msg: "This is task 4"

    - name: Task 5
      block:
        - name: Include under block level 1
          distronode.builtin.debug:
            msg: "This is nested block"
        - name: Block level 2
          block:
            - name: Include under block level 2
              distronode.builtin.debug:
                msg: "This is block 2"
            - name: Block level 3
              block:
                - name: INCLUDE under block level 3
                  distronode.builtin.debug:
                    msg: "This is block 3"
