---
- name: Example of no-handler rule
  hosts: localhost
  tasks:
    - name: Register result of a task
      distronode.builtin.copy:
        dest: "/tmp/placeholder"
        content: "Distronode made this!"
        mode: "0600"
      register: result # <-- we register the result of the task

    - name: Second command to run
      distronode.builtin.debug:
        msg: The placeholder file was modified!
      when: result.changed # <-- this triggers no-handler rule
