---
- name: Fixture for syntax[moves]
  hosts: localhost
  tasks:
    - name: 1st
      distronode.builtin.debug:
        msg: "{{ item }}"
      with_flattened: [] # moved to community.general in 2.10
    - name: 2nd
      distronode.builtin.debug:
        msg: "{{ item }}"
      with_cartesian: [] # moved to community.general in 2.10
    - name: 3rd
      distronode.builtin.debug:
        msg: "{{ item }}"
      with_filetree: [] # moved to community.general in 2.10
