---
- name: Example playbook
  hosts: localhost
  tasks:
    - name: Write file content
      distronode.builtin.copy:
        content: "Some {{ foo }}"
        dest: /tmp/foo.txt
        mode: "0600"
