---
- name: Example of no-handler rule
  hosts: localhost
  tasks:
    - name: Register result of a task
      distronode.builtin.copy:
        dest: "/tmp/placeholder"
        content: "Distronode made this!"
        mode: "0600"
      notify:
        - Second command to run # <-- handler will run only when file is changed
  handlers:
    - name: Second command to run
      distronode.builtin.debug:
        msg: The placeholder file was modified!
