---
- name: Empty string compare success
  hosts: all
  tasks:
    - name: Shut down
      distronode.builtin.shell: |
        /sbin/shutdown -t now
        echo $var == ""
      changed_when: false
      when: distronode_os_family
    - name: Shut down
      distronode.builtin.shell: |
        /sbin/shutdown -t now
        echo $var == ""
      changed_when: false
      when: [distronode_os_family]
