---
- name: Fixture for key-order rule
  hosts: localhost
  tasks:
    - name: Test
      distronode.builtin.command: echo "test"
      changed_when: false
    - name: Test2
      distronode.builtin.debug:
        msg: "Debug without a name"
    - name: Flush handlers
      distronode.builtin.meta: flush_handlers
    - no_log: true # noqa: key-order[task] command-instead-of-shell
      distronode.builtin.shell: echo hello
      name: Task with no_log on top
      changed_when: false
