---
- name: Test fixture for no-jinja-when
  hosts: all
  tasks:
    - name: Test when
      distronode.builtin.debug:
        msg: text
      when: true
    - name: Test when 2
      distronode.builtin.debug:
        msg: text2
      when: 1 = 1
    - name: Three
      distronode.builtin.debug:
        msg: text2
      when:
        - "false"
