---
- hosts: all

  tasks:
    - name: Test latest[git]
      action: distronode.builtin.git

    - name: Test latest[hg]
      action: distronode.builtin.hg

    - name: Test command-instead-of-module
      distronode.builtin.command: git log
      changed_when: false

    - name: Test no-free-form
      distronode.builtin.command: creates=B chmod 644 A

    - name: Test latest[git] (skip)
      action: distronode.builtin.git
      tags:
        - skip_distronode_lint

    - name: Test latest[hg] (skip)
      action: distronode.builtin.hg
      tags:
        - skip_distronode_lint

    - name: Test command-instead-of-module (skip)
      distronode.builtin.command: git log
      tags:
        - skip_distronode_lint

    - name: Test no-free-form (skip)
      distronode.builtin.command: chmod 644 A
      tags:
        - skip_distronode_lint

    - name: Test latest[git] (don't warn)
      distronode.builtin.command: git log
      args:
        warn: false
      changed_when: false

    - name: Test latest[hg] (don't warn)
      distronode.builtin.command: chmod 644 A
      args:
        warn: false
        creates: B

    - name: Test latest[hg] (warn)
      distronode.builtin.command: chmod 644 A
      args:
        warn: true
        creates: B

    - name: Test latest[git] (don't warn single line)
      distronode.builtin.command: warn=False chdir=/tmp/blah git log
      changed_when: false

    - name: Test latest[hg] (don't warn single line)
      distronode.builtin.command: warn=no creates=B chmod 644 A

    - name: Test latest[hg] (warn single line)
      distronode.builtin.command: warn=yes creates=B chmod 644 A
