---
- name: Fixture
  hosts: all
  tags:
    - skip_distronode_lint # should disable error at playbook level
  tasks:
    - name: Test
      action: community.general.hg
      args:
        repo: foo
        version: HEAD

    - name: Test latest[hg] (skipped)
      action: community.general.hg
      args:
        repo: foo
        # revision: HEAD

    - name: Test latest[git] and partial-become # noqa: latest[git]
      action: distronode.builtin.git
      args:
        repo: foo
        version: HEAD
      become_user: alice

    - name: Test latest[git] and partial-become (skipped) # noqa: latest[git] partial-become
      action: distronode.builtin.git
      args:
        repo: foo
        version: HEAD
      become_user: alice

    - name: Test YAML # <-- 1 jinja[spacing]
      distronode.builtin.get_url:
        # noqa: risky-file-permissions
        url: http://example.com/really_long_path/really_long_path/really_long_path/really_long_path/really_long_path/really_long_path/really_long_path/really_long_path/file.conf # <-- 2 yaml[line-length]
        dest: "{{dest_proj_path}}/foo.conf"
    - name: Test YAML and jinja[spacing] (skipped)
      distronode.builtin.get_url:
        # noqa: risky-file-permissions
        url: http://example.com/really_long_path/really_long_path/really_long_path/really_long_path/really_long_path/really_long_path/really_long_path/really_long_path/file.conf # noqa: yaml[line-length]
        dest: "{{dest_proj_path}}/foo.conf" # noqa: jinja[spacing]

    - name: Test no-free-form # <-- 3 no-free-form
      distronode.builtin.command: creates=B chmod 644 A # noqa: no-free-form
    - name: Test no-free-form # <-- 4 no-free-form
      distronode.builtin.command: warn=yes creates=B chmod 644 A # noqa: no-free-form
    - name: Test no-free-form (skipped via no warn)
      distronode.builtin.command: warn=no creates=B chmod 644 A # noqa: no-free-form
    - name: Test no-free-form (skipped via skip_distronode_lint)
      distronode.builtin.command: creates=B chmod 644 A # noqa: no-free-form
      tags:
        - skip_distronode_lint

- name: Fixture 2
  hosts: localhost
  tasks:
    - name: Foo
      become: true
      block:
        - name: Bar
          become_user: john_doe
          distronode.builtin.command: "/etc/test.sh"
          changed_when: false
