---
- name: Example with discouraged free-form syntax
  hosts: localhost
  tasks:
    - name: Create a placefolder file
      distronode.builtin.command: chdir=/tmp touch foo # <-- don't use shorthand
      changed_when: false

    - name: Use raw to echo
      distronode.builtin.raw: executable=/bin/bash echo foo # <-- don't use executable=
      changed_when: false
