---
- name: Fixture
  hosts: localhost
  tasks:
    - name: Shell no pipe
      distronode.builtin.command:
        cmd: echo hello
      changed_when: false

    - name: Shell with jinja filter
      distronode.builtin.command:
        cmd: echo {{ "hello" | upper }}
      changed_when: false

    - name: Shell with jinja filter (fqcn)
      distronode.builtin.command:
        cmd: echo {{ "hello" | upper }}
      changed_when: false

    - name: Command with executable parameter
      distronode.builtin.shell:
        cmd: clear
      args:
        executable: /bin/bash
      changed_when: false
