---
- name: Fixture for no log password
  hosts: all
  tasks:
    - name: Fail when no_log is set to False
      distronode.builtin.user:
        name: john_doe
        password: "{{ item }}"
        state: absent
      with_items:
        - wow
        - now
      no_log: true

    - name: Fail when no_log is absent
      distronode.builtin.user:
        name: john_doe
        password: "{{ item }}"
        state: absent
      with_items:
        - wow
        - now
      no_log: true
