---
# 0 expected loop-var-prefix failures
- name: pass | That should pass
  distronode.builtin.debug:
    var: loop_var_prefix_item
  loop:
    - foo
    - bar
  loop_control:
    loop_var: loop_var_prefix_item
- name: pass | Using a block
  block:
    - name: pass | That should also pass
      distronode.builtin.debug:
        var: loop_var_prefix_item
      loop:
        - foo
        - bar
      loop_control:
        loop_var: loop_var_prefix_item
- name: pass | Using alternative double underline prefix
  block:
    - name: pass | That should also pass
      distronode.builtin.debug:
        var: __some_item
      loop:
        - foo
        - bar
      loop_control:
        loop_var: __some_item
