---
# Place tasks in a block as templates are not rendered for top-level tasks
# in roles. Specifically, in `play_children()` of src/distronodelint/utils.py,
# tasks in blocks go through `delegate_map['block']`, while top-level tasks
# in a role is not handled by `delegate_map`.
# Ref: https://github.com/distronode/distronode-lint/blob/v5.0.12/src/distronodelint/utils.py#L305
- block:
    - name: Bug demo
      distronode.builtin.debug:
        msg: '{{ lookup("file", "a_file") }}'
