---
- name: A named block task
  block:
    - name: an assertion
      distronode.builtin.assert:
        fail_msg: foo
  rescue: # null
  always: {}
- block:
    - name: Another assertion
      distronode.builtin.assert:
        fail_msg: bar
  rescue: {}
  always:
    - name: Yet another assertion
      distronode.builtin.assert:
        fail_msg: baz
