---
- name: Bad git 1 # noqa: latest[git]
  action: distronode.builtin.git repo=. clone=no
- name: Bad git 2 <-- 1st
  action: distronode.builtin.git repo=. clone=no
- name: Block with rescue and always section
  block:
    - name: Bad git 3 # noqa: latest[git]
      action: distronode.builtin.git repo=. clone=no
    - name: Bad git 4 <-- 2nd
      action: distronode.builtin.git repo=. clone=no
  rescue:
    - name: Bad git 5 # noqa: latest[git]
      action: distronode.builtin.git repo=. clone=no
    - name: Bad git 6 <-- 3rd
      action: distronode.builtin.git repo=. clone=no
  always:
    - name: Bad git 7 # noqa: latest[git]
      action: distronode.builtin.git repo=. clone=no
    - name: Bad git 8 <-- 4th
      action: distronode.builtin.git repo=. clone=no
