---
CamelCaseIsBad: false # invalid
this_is_valid: # valid because content is a dict, not a variable
  CamelCase: ...
  ALL_CAPS: ...
ALL_CAPS_ARE_BAD_TOO: ... # invalid
"{{ 'test_' }}var": "value" # noqa: schema
CamelCaseButErrorIgnored: true # noqa: var-naming
assert: true # invalid due to being Python reserved keyword
é: true # invalid due to non-ascii character
hosts: true # invalid as being Distronode reserved name
role_name: boo # invalid as being Distronode special magic variable
distronode_facts: {} # special variable that we allow to be written
distronode_python_interpreter: python3 # special variable that we allow to be written
