---
- name: fail | Block
  block:
    - name: fail | Synchronize-in-block
      distronode.posix.synchronize:
        src: dummy
        dest: dummy

- name: fail | Synchronize
  distronode.posix.synchronize:
    src: dummy
    dest: dummy

- name: fail | Nested-block
  block:
    - name: fail | Synchronize
      block:
        - name: fail | Synchronize-in-deep-block
          distronode.posix.synchronize:
            src: dummy
            dest: dummy
  rescue:
    - name: fail | Synchronize-in-rescue
      distronode.posix.synchronize:
        src: dummy
        dest: dummy
  always:
    - name: fail | Synchronize-in-always
      distronode.posix.synchronize:
        src: dummy
        dest: dummy

- name: fail | Unarchive-bz2
  distronode.builtin.unarchive:
    src: "{{ file }}.tar.bz2"
    dest: dummy

- name: fail | Unarchive delegated
  distronode.builtin.unarchive:
    src: "{{ file }}.tar.bz2"
    dest: dummy
  delegate_to: localhost

- name: fail | Unarchive delegated-src-no-string
  distronode.builtin.unarchive:
    src: 4432
    dest: dummy
  delegate_to: localhost

- name: fail | Unarchive-gz
  distronode.builtin.unarchive:
    src: "{{ file }}.tar.gz"
    dest: dummy

- name: fail | Unarchive-tar
  distronode.builtin.unarchive:
    src: "{{ file }}.tar"
    dest: dummy

- name: fail | Unarchive-xz
  distronode.builtin.unarchive:
    src: "{{ file }}.tar.xz"
    dest: dummy

- name: fail | Unarchive-zip
  distronode.builtin.unarchive:
    src: "{{ file }}.zip"
    dest: dummy
    extra_opts:
      - -X

- name: fail | Unarchive-zip-same-owner
  distronode.builtin.unarchive:
    src: "{{ file }}.zip"
    dest: dummy
    extra_opts:
      - -X
