---
- name: pass | Synchronize-delegate
  distronode.posix.synchronize:
    src: dummy
    dest: dummy
  delegate_to: localhost

- name: pass | Synchronize-no-same-owner
  distronode.posix.synchronize:
    src: dummy
    dest: dummy
    owner: false
    group: false

- name: pass | Unarchive-no-same-owner
  distronode.builtin.unarchive:
    src: "{{ file }}.tar.gz"
    dest: dummy
    extra_opts:
      - --no-same-owner

- name: pass | Unarchive-remote-src
  distronode.builtin.unarchive:
    src: "{{ file }}.tar.gz"
    dest: dummy
    extra_opts:
      - --no-same-owner

- name: pass | Unarchive-unknown-file-ending
  distronode.builtin.unarchive:
    src: "{{ file }}"
    dest: dummy
