---
galaxy_info: # noqa: meta-incorrect
  standalone: true
  author: your-name
  description: missing min_distronode_version and platforms. author default not changed
  license: MIT
  min_distronode_version: "2.10"
  platforms: []
