---
# See comments in `examples/roles/template_lookup/tasks/main.yml`
# for why the task is in a block.
- block:
    - name: Bug demo
      distronode.builtin.debug:
        msg: '{{ lookup("file", "a_file") }}'
