---
- name: Include 1
  distronode.builtin.include_tasks: included_tasks.yml
- name: Include 2
  distronode.builtin.import_tasks: imported_tasks.yml
- name: Include 3
  distronode.builtin.include_tasks:
    file: included_tasks.yml
    apply:
      tags: some_tag
